const searchActionTypes = {
  SET_CITY_SEARCH: 'SET_CITY_SEARCH',
  SET_REFINED_SEARCH: 'SET_REFINED_SEARCH',
  CLEAR_CITY_SEARCH: 'CLEAR_CITY_SEARCH',
  CLEAR_REFINED_SEARCH: 'CLEAR_REFINED_SEARCH',
  GET_FILTERED_RESULTS: 'GET_FILTERED_RESULTS'
}

export default searchActionTypes
